export const subServicesList = [
  {
    title: "Space Planning",
    image: "/testImg1.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Design Conceptualization",
    image: "/testImg2.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "2D/3D Visualization",
    image: "/testImg3.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Material Selection",
    image: "/testImg4.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Furniture Designing",
    image: "/testImg5.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Colour Consultaion",
    image: "/testImg6.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Project Management",
    image: "/testImg7.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Project Management",
    image: "/testImg8.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Sustainable Design",
    image: "/testImg9.jpeg",
    location: "London",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
];

export const ProjectsList = [
  {
    title: "Central Saint Giles",
    para: "Nanchang Wave is a landscape based community centre with a varied program forming the heart of a large residential development. The double helix structure towards the wetland area gives 360 degrees overview of the neighbourhood as one walks up to the panoramic gallery at top.",
    image: "/testImg1.jpeg",
    location: "London",
    year: "2009",
    area: "70000", // in m square
    client: "Vanke",
    constructionCost: "130 mil NOK",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Central Saint Giles",
    para: "Nanchang Wave is a landscape based community centre with a varied program forming the heart of a large residential development. The double helix structure towards the wetland area gives 360 degrees overview of the neighbourhood as one walks up to the panoramic gallery at top.",
    image: "/testImg1.jpeg",
    location: "London",
    year: "2009",
    area: "70000", // in m square
    client: "Vanke",
    constructionCost: "130 mil NOK",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Central Saint Giles",
    para: "Nanchang Wave is a landscape based community centre with a varied program forming the heart of a large residential development. The double helix structure towards the wetland area gives 360 degrees overview of the neighbourhood as one walks up to the panoramic gallery at top.",
    image: "/testImg1.jpeg",
    location: "London",
    year: "2009",
    area: "70000", // in m square
    client: "Vanke",
    constructionCost: "130 mil NOK",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Central Saint Giles",
    para: "Nanchang Wave is a landscape based community centre with a varied program forming the heart of a large residential development. The double helix structure towards the wetland area gives 360 degrees overview of the neighbourhood as one walks up to the panoramic gallery at top.",
    image: "/testImg1.jpeg",
    location: "London",
    year: "2009",
    area: "70000", // in m square
    client: "Vanke",
    constructionCost: "130 mil NOK",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Central Saint Giles",
    para: "Nanchang Wave is a landscape based community centre with a varied program forming the heart of a large residential development. The double helix structure towards the wetland area gives 360 degrees overview of the neighbourhood as one walks up to the panoramic gallery at top.",
    image: "/testImg1.jpeg",
    location: "London",
    year: "2009",
    area: "70000", // in m square
    client: "Vanke",
    constructionCost: "130 mil NOK",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
  {
    title: "Central Saint Giles",
    para: "Nanchang Wave is a landscape based community centre with a varied program forming the heart of a large residential development. The double helix structure towards the wetland area gives 360 degrees overview of the neighbourhood as one walks up to the panoramic gallery at top.",
    image: "/testImg1.jpeg",
    location: "London",
    year: "2009",
    area: "70000", // in m square
    client: "Vanke",
    constructionCost: "130 mil NOK",
    moreImg: [
      { src: "/subImg1.jpeg", title: "Front facades" },
      { src: "/subImg2.jpeg", title: "Front facades from sides" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
      { src: "/subImg3.jpeg", title: "Front facades close up" },
      { src: "/subImg4.jpeg", title: "Front facades Close up" },
    ],
  },
];
